logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              
# 동작 환경 설정
spring:
  profiles:
    active: prod

server:
  servlet:
    session:
      timeout: 43200m      # 60m * 24h * 30d
      cookie:
        max-age: 43200m    # 60m * 24h * 30d
        name: SID
        http-only: true
        secure: true       
# 동작 환경 설정

      
---
spring:
  config:
    activate: 
      on-profile: test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: dustp1357!@
    url: jdbc:mariadb://203.245.44.51:3306/suyonsei?useUnicode=true&characterEncoding=utf8
    username: suyonsei
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: -1
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'admin@smilelasek.com'
    password: 'xeexpnoaacwnmdjj'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# 배포 환경
--- 
spring:
  config:
    activate: 
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: dustp1357!@
    url: jdbc:mariadb://localhost:3306/suyonsei?useUnicode=true&characterEncoding=utf8
    username: suyonsei
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: -1
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'admin@smilelasek.com'
    password: 'xeexpnoaacwnmdjj'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true